second refactor
Star-Academy/Summer1401-SE-Team01 pull request #1
Opened 2022-07-20 08:37 UTC by aliEm2001

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/Doc.java
>      }
فایلای باینری و کلا پوشه out باید بره توی gitignore
نیاد روی مستر

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/Doc.java
> +        string.replaceAll("[./?!,:\'\"]", "");
مطمئنین این کار میکنه؟!
استرینگ immutableهستش
باید بنویسین:
string = string.replaceAll("[./?!,:\'\"]", "");

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/Doc.java
> -        string = string.replace(".", "");
بالا نمیشد کامنت بزنم
خط 12 documentName_  قاعده نامگذاریش رو جایی دیدین؟

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/FileReader.java
>              Scanner scanner = new Scanner(file);
Contex
خط 17 اصلاح شه

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/SearchEngine.java
>          ArrayList<Doc> documents = FileReader.readFiles();
کلاسای سطح بالا نباید به کلاسای سطح پایین وابسته باشن
همون dependency inversion
این جا SearchEngine نباید بدونه لیست فایلا از کجا میاد
ی اینترفیس باید ورودی بگیره که مثلا ی متد getDocsList داشته باشه.

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/SearchEngine.java
>          SplitedInput splitedInput = Input.prepareInput();
اینم مثل قبلی

2022-07-20 09:59 UTC, abolfazlghalandary commented on Search/src/com/InvertedIndex.java
> +    public static HashSet<Doc> findIncludeOne(ArrayList<String> includeOne, HashSet<Doc> selectedFiles) {
سر استاتیک کردن هر دو تیم مسئله داشتین
فعلا اوکیه 
ولی توی جلسه صحبت کنیم

2022-07-20 12:28 UTC, Soltaniant requested changes
it has some logical errors which effect search engine functionality. please pay more attention to the core of search engine.

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/FileReader.java
> -                documents.add(new Doc(filesName[i], contex));
File Reader should be only responsible for reading a file, not to load and store all files.
*-Single Responsibility Principle*

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/Doc.java
>          words = tokenizeString(contex);
Tokenizing and removing ponctuations should be performed by a seperate class.
*-Single Responsibility Principle*

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/FileReader.java
>          for (int i = 0; i < filesName.length; i++) {
Nit: "fileNames" is better than "filesName"

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/Input.java
> +                splitedInput.getIncludeAll().add(word);
using getter methods to add data to your object is not recommended. though it's been passed by reference.

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/FileReader.java
>                  File file = new File("tests/" + filesName[i]);
folder name containing documents should be used as a config file. imagine that your folder name will be changed, then you should look around your codes to find where did you use "tests/" to change it.

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/InvertedIndex.java
> +        findExcludeAll(splitedInput.getExcludeAll(), selectedFile);
returned value of functions are not used! => the final answer is logically wrong :(

2022-07-20 12:28 UTC, Soltaniant commented on Search/src/com/SplitedInput.java
> +    public ArrayList<String> getExcludeAll () { return excludeAll; }
no setter method is used. instead you are passing objects by reference and modify them.

2022-07-20 13:02 UTC, smhh22 commented on Search/src/com/Input.java
> +                splitedInput.getIncludeAll().add(word);
چرا؟

2022-07-20 15:00 UTC, smhh22 commented on Search/src/com/FileReader.java
> -                documents.add(new Doc(filesName[i], contex));
خب الان فایلو بخونه باید یه جا ذخیره کنه دیگه. خوندن و لود کردن هم که تقریبا یکین

2022-07-20 15:00 UTC, smhh22 commented on Search/src/com/Doc.java
>          words = tokenizeString(contex);
یه کلاسی داریم که وظیفه‌ش اینه که کلمات یه استرینگ رو استخراج کنه دیگه
کجای کار نقض شده؟

2022-07-20 15:05 UTC, smhh22 commented on Search/src/com/InvertedIndex.java
> +        findExcludeAll(splitedInput.getExcludeAll(), selectedFile);
بخاطر اینکه رفرنس پاس داده میشه مشکلی نیست. تقریبا voidن.

2022-07-20 15:08 UTC, smhh22 commented on Search/src/com/SplitedInput.java
> +    public ArrayList<String> getExcludeAll () { return excludeAll; }
این هم همون مشکلیه که بالاتر گرفتی و پرسیدم چرا

2022-07-21 05:15 UTC, Soltaniant commented on Search/src/com/FileReader.java
> -                documents.add(new Doc(filesName[i], contex));
اینو شک دارم. چون آقای حیدر زاده هم یه ایراد این شکلی از ما گرفت. ولی اوکی

2022-07-21 05:19 UTC, Soltaniant commented on Search/src/com/Doc.java
>          words = tokenizeString(contex);
کلاسی به اسم document داریم که طبق اسمش باید شامل متن و نام یک داکیومنت باشه. فرض کن برای یه کاربرد دیگه بخوای از همین کلاس استفاده کنی. و توی اون کاربرد هم نیازی به توکنایز کردن و غیره نداری. در این صورت نمیشه از این کلاس استفاده کرد چون یه سری متود اضافه داره. بهتره که موجودیت tokenizer یه چیز مجزایی باشه. خود فرایند tokenizing یه پروسه ای داره که خیلی بیشتر از صرف جدا کردن کلماته. هر چند ما اینجا پیشرفته بهش نگاه نکردیم.

2022-07-21 05:22 UTC, Soltaniant commented on Search/src/com/Input.java
> +                splitedInput.getIncludeAll().add(word);
چون توی جاوا داره pass by reference فیلد ما return میشه. از این موضوع نباید سو استفاده کرد و مقدار فیلد رو تغییر داد. این جوری الان از هر جایی از برنامه به این فیلد دسترسی وجود داره و انگار که اصلا public  تعریف شده.

2022-07-21 05:24 UTC, Soltaniant commented on Search/src/com/InvertedIndex.java
> +        findExcludeAll(splitedInput.getExcludeAll(), selectedFile);
مورد اول اینکه جواب در هر صورت غلطه. تست کن حتما برنامه رو
مورد دوم اینکه میدونم pass by refrence هست. اما بازم همون حرف قبلی رو میشه زد. داریم فیلد رو مستقیما دستکاری میکنیم. به علاوه اینکه اگر void هست خب از اول void چرا تعریف نکردیم؟

2022-07-21 05:28 UTC, Soltaniant requested changes
عملکرد کد اشتباه است.

2022-07-21 05:28 UTC, Soltaniant commented on Search/src/com/Doc.java
>          words = tokenizeString(contex);
.

2022-07-21 05:28 UTC, Soltaniant commented on Search/src/com/Input.java
> +                splitedInput.getIncludeAll().add(word);
.

2022-07-21 05:28 UTC, Soltaniant commented on Search/src/com/InvertedIndex.java
> +        findExcludeAll(splitedInput.getExcludeAll(), selectedFile);
.

2022-07-22 12:22 UTC, Soltaniant approved these changes

2022-07-22 12:22 UTC, Soltaniant commented on Search/src/com/SearchEngine.java
> +        InvertedIndex.addDocuments(documents);
اینجا داری استاتیک کاری میکنی و دو تا کلاس به هم وابسه هم هستن. جلوتر ایراد میگیرن از این. توضیحش رو هم منتور جونیور توی جلسه داد اگر یادت باشه

2022-07-22 12:54 UTC, smhh22 commented on Search/src/com/SearchEngine.java
> +        InvertedIndex.addDocuments(documents);
استاتیک بودن رو که آره. البته ابوالفضل گفت این سری مشکلی نیست.
وولی اون وابسته بودنه از این لحاظ منطقی نیست که هر search engine واقعا یدونه inverted index داره؟

2022-07-22 12:55 UTC, smhh22 approved these changes

2022-07-22 14:24 UTC, abolfazlghalandary approved these changes

2022-07-24 05:05 UTC, mohammadhheidarzade requested changes

2022-07-24 05:05 UTC, mohammadhheidarzade commented on .gitignore
> +/Search/out/
احسنت

.class ها به نظر همچنان در ریپو هستند
حذف شوند

2022-07-24 05:05 UTC, mohammadhheidarzade commented on Search/src/com/FileReader.java
> -                documents.add(new Doc(filesName[i], contex));
بله درسته. از اسم کلاس مشخصه وظیفه‌ی خواندن فایل رو بر عهده داره نه ذخیره سازی

2022-07-24 05:05 UTC, mohammadhheidarzade commented on Search/src/com/Doc.java
> +//    @Override
کامنت ها حذف بشن

2022-07-24 05:51 UTC, mohammadhheidarzade approved these changes

2022-07-24 05:53 UTC, merged