Ef core
Star-Academy/Summer1401-SE-Team01 pull request #5
Opened 2022-08-10 07:57 UTC by smhh22

2022-08-13 06:21 UTC, abolfazlghalandary requested changes

2022-08-13 06:21 UTC, abolfazlghalandary commented on EFCore/Database Updater/Program.cs
> +foreach (var grade in grades)
به عنوان ی متد استخراج شه فهم کد بره بالا

2022-08-13 06:21 UTC, abolfazlghalandary commented on EFCore/Models/SchoolContext.cs
> +
اینتر اضافس

2022-08-13 06:21 UTC, abolfazlghalandary commented on EFCore/Models/bin/Debug/net6.0/Models.deps.json
> +{
نیاددددددد توی مستر

2022-08-13 06:21 UTC, abolfazlghalandary commented on EFCore/Models/bin/Debug/net6.0/Models.runtimeconfig.json
> +  "runtimeOptions": {
.

2022-08-13 06:21 UTC, abolfazlghalandary commented on SearchTDD/Search.Test/obj/Debug/net6.0/Search.Test.AssemblyInfoInputs.cache
> +18d7b2e38808fc429d9b8977347bf4dfc93990a5
.

2022-08-13 06:21 UTC, abolfazlghalandary commented on SearchTDD/Search/obj/rider.project.restore.info
> +﻿16600369944730551
هیچ کدوم از فایلای bin و obj نیاد مستر

2022-08-13 15:05 UTC, abolfazlghalandary approved these changes
به جز پوشه bin و obj اوکی بود همه چی
دمتون گرم

2022-08-13 15:05 UTC, abolfazlghalandary commented on SearchTDD/Search.Test/obj/Debug/net6.0/Search.Test.csproj.FileListAbsolute.txt
> +C:\Users\Ali\Summer1401-SE-Team01\SearchTDD\Search.Test\bin\Debug\net6.0\CoverletSourceRootsMapping
!

2022-08-13 15:05 UTC, abolfazlghalandary commented on SearchTDD/Search.Test/obj/Debug/net6.0/Search.Test.csproj.CoreCompileInputs.cache
> +3f01628ba57c91f8393bc70de4fec53dc367ebaa
!

2022-08-13 15:05 UTC, abolfazlghalandary commented on SearchTDD/Search.Test/obj/Search.Test.csproj.nuget.dgspec.json
> +{
قرار شد نیاد

2022-08-14 05:10 UTC, heidarzade-mh approved these changes

2022-08-14 05:10 UTC, heidarzade-mh commented on EFCore/Models/SchoolContext.cs
> +        optionsBuilder.UseNpgsql("Server=127.0.0.1;Port=5432;Database=school;User Id=postgres;Password=postgres;");
connectionstring
به صورت کانفیگی بشه

2022-08-14 06:44 UTC, Soltaniant approved these changes

2022-08-14 06:44 UTC, Soltaniant commented on EFCore/Database Updater/Program.cs
> +const string gradesFilePath = @"./grades.json";
can be moved to `Config.cs` file

2022-08-14 06:44 UTC, Soltaniant commented on EFCore/Models/Config.cs
> +    public static readonly string password = "password";
Great :)

2022-08-14 06:44 UTC, Soltaniant commented on EFCore/Models/Grade.cs
> +        return Id + " " + Lesson + " " + Score + "\n";
Nit: using string interrogator would be better.

2022-08-14 06:44 UTC, Soltaniant commented on EFCore/Query/Program.cs
> +    var answer = context.Students.Include(s => s.Grades)
Nit: `answer` is not appropriate name. (ex: `topStudents` might be better)

2022-08-14 06:50 UTC, merged